apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "du-upgrade"
  namespace: "ztp-group"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  remediationAction: inform
  sourceFiles:
    - fileName: ImageSignature.yaml 
      policyName: "platform-upgrade-prep"
      binaryData:
        -:  
    - fileName: DisconnectedICSP.yaml
      policyName: "platform-upgrade-prep"
      metadata:
        name: disconnected-internal-icsp-for-ocp
      spec:
        repositoryDigestMirrors: 
          - mirrors:
            - test07.gpskr.local:5000/ocp412/openshift5/openshift/release
            source: quay.io/openshift-release-dev/ocp-release
          - mirrors:
            - test07.gpskr.local:5000/ocp412/openshift5/openshift/release
            source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    - fileName: ClusterVersion.yaml 
      policyName: "platform-upgrade-prep"
      metadata:
        name: version
        annotations:
          ran.openshift.io/ztp-deploy-wave: "1"
      spec:
        channel: "stable-4.12"
        upstream: http://bastion.dual.local:8888/images/upgrade-graph_stable-4.12
        desiredUpdate:
          image: test07.gpskr.local:5000/ocp412/openshift5/openshift/release-images@sha256:fd65cebce150bac3c622e30e7f762d3173575ae3541b3a7648819cb63e9b63a4
    - fileName: ClusterVersion.yaml 
      policyName: "platform-upgrade"
      metadata:
        name: version
      spec:
        channel: "stable-4.12"
        upstream: http://bastion.dual.local:8888/images/upgrade-graph_stable-4.12
        desiredUpdate:
          image: test07.gpskr.local:5000/ocp412/openshift5/openshift/release-images@sha256:fd65cebce150bac3c622e30e7f762d3173575ae3541b3a7648819cb63e9b63a4
      status:
        history:
          - image: test07.gpskr.local:5000/ocp412/openshift5/openshift/release-images@sha256:fd65cebce150bac3c622e30e7f762d3173575ae3541b3a7648819cb63e9b63a4
            state: "Completed"
