apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno1"
  namespace: "sno1"
spec:
  baseDomain: "dual.local"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "openshift-4.12.1.0"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD1+HG7pZeDFAHqlConDJj/Lp6hcBm539dFErOuIb+VgSecZtyGbpkLU+GxNicCUF8c9KQmq86woEnVmDy75PaEDmUs1ncEeNzpK33N1Y9gzOHdxafjXBPh+d/XWXsOuqdkE173zJ7Th4yBMNVHY/5WBgvXJgkiFM9oZMEM6JNuZ3ihm8TdJLmnMze7VKruZkuN2W7addVoHkqKJpLArhAVNNfAKhMyx40PapZzVk8emJ2wgm6AlGDsueHDI2SbysJ5hmJuG7YaryUkhb+mZlSQZXyEIgIbAiFmen9X0LrCiYgaBL9/2YHTQvxhw6izP3WeQyJfJk9hCf9zWSZonMYs4cXs1+bITz+a7QYQnUfSN2kPw/nKBW5tV5MlKuRwE3CEd4ltN9Tg5MDZy7vkABxSif1J/DnUPldrY4EQnZh0kCa11w8Gq6F/XzIK3deiYlMoO+CA6fkLZz0xkWckx20jfE4oXeGQ8oGEZIH/Elk1ANbgO1stCynRYJnIQ0i2zbhtp0EYIexTh8+gg1vgrRh5VkRmcALWlFC0pdA4XKHKJDA+oYXDTkQdWPQ+sHeT6q662HPdi9Ylq6iSkLXyPPg5K5Yo8LlGVS7SbqaPFXG5ibLDziTEHZkHqVXoO/64BishsgMMwDJe/7H9I0f7XTs1Hv3SkiDsPR1tVQAFKGIjYw== root@bastion.dual.local"
  clusters:
  - clusterName: "sno1"
    networkType: "OVNKubernetes"
    clusterLabels:
      sites : "sno1"
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    machineNetwork:
    - cidr: 192.168.10.0/24
    serviceNetwork:
    - 172.30.0.0/16
    nodes:
    - hostName: "node.sno1.dual.local"
      role: "master"
      bmcAddress: "redfish-virtualmedia+http://192.168.10.1:8000/redfish/v1/Systems/b3b3e9c5-2d51-49d8-903f-2ee45960b203"
      bmcCredentialsName:
        name: "sno1-bmc-secret"
      bootMACAddress: "00:ef:41:21:e1:a1"
      bootMode: "UEFI"
      rootDeviceHints:
        deviceName: "/dev/vda"
      nodeNetwork:
        interfaces:
        - name: enp1s0
          macAddress: "00:ef:41:21:e1:a1"
        config:
          interfaces:
          - name: enp1s0
            type: ethernet
            state: up
            macAddress: "00:ef:41:21:e1:a1"
            ipv4:
              enabled: true
              address:
              - ip: 192.168.10.60
                prefix-length: 24
              dhcp: false
            ipv6:
              enabled: false
            mtu: 9000
          dns-resolver:
            config:
              server:
              - 192.168.10.100
          routes:
            config:
            - destination: 0.0.0.0/0
              next-hop-address: 192.168.10.1
              next-hop-interface: enp1s0
              table-id: 254
